package ipcm.counter.testapp2;

import java.util.HashMap;
import java.util.Map;


/**
 * Created by npmstudent on 1/17/18.
 */

class ColorList {
    static Map<String, String> colorReference = new HashMap<>();

    ColorList() {
        for (int i = 0; i < colorArray.length; i++) {
            colorReference.put(colorArray[i].toLowerCase().trim(), colorCodeArray[i].trim());
        }
    }

    static boolean isColorName(String input) {
        if (colorReference.containsKey(input)) {
            System.out.println(colorReference.get(input));
            return true;
        }
        System.out.println("Not working");
        return false;
    }

    static String getColor(String input) {
        return input.substring(0, 1).toUpperCase() + input.substring(1);
    }

    static String getColorCode(String input) {
        return colorReference.get(input);
    }

    final String[] colorArray = {"White",
            "Ivory",
            "Light Yellow",
            "Yellow",
            "Snow",
            "Floral White",
            "Lemon Chiffon",
            "Cornsilk",
            "Seashell",
            "Lavender Blush",
            "Papaya Whip",
            "Blanched Almond",
            "Misty Rose",
            "Bisque",
            "Moccasin",
            "Navajo White",
            "Peach Puff",
            "Gold",
            "Pink",
            "Light Pink",
            "Orange",
            "Light Salmon",
            "Dark Orange",
            "Coral",
            "Hot Pink",
            "Tomato",
            "Orange Red",
            "Deep Pink",
            "Fuchsia",
            "Magenta",
            "Red",
            "Old Lace",
            "Light Goldenrod Yellow",
            "Linen",
            "Antique White",
            "Salmon",
            "Ghost White",
            "Mint Cream",
            "White Smoke",
            "Beige",
            "Wheat",
            "Sandy Brown",
            "Azure",
            "Honeydew",
            "Alice Blue",
            "Khaki",
            "Light Coral",
            "Pale Goldenrod",
            "Violet",
            "Dark Salmon",
            "Lavender",
            "Light Cyan",
            "Burly Wood",
            "Plum",
            "Gainsboro",
            "Crimson",
            "Pale Violet Red",
            "Goldenrod",
            "Orchid",
            "Thistle",
            "Light Grey",
            "Tan",
            "Chocolate",
            "Peru",
            "Indian Red",
            "Medium Violet Red",
            "Silver",
            "Dark Khaki",
            "Rosy Brown",
            "Medium Orchid",
            "Dark Goldenrod",
            "Fire Brick",
            "Powder Blue",
            "Light Steel Blue",
            "Pale Turquoise",
            "Green Yellow",
            "Light Blue",
            "Dark Gray",
            "Brown",
            "Sienna",
            "Yellow Green",
            "Dark Orchid",
            "Pale Green",
            "Dark Violet",
            "Medium Purple",
            "Light Green",
            "Dark Sea Green",
            "Saddle Brown",
            "Dark Magenta",
            "Dark Red",
            "Blue Violet",
            "Light Sky Blue",
            "Sky Blue",
            "Gray",
            "Olive",
            "Purple",
            "Maroon",
            "Aquamarine",
            "Chartreuse",
            "Lawn Green",
            "Medium Slate Blue",
            "Light Slate Gray",
            "Slate Gray",
            "Olive Drab",
            "Slate Blue",
            "Dim Gray",
            "Medium Aquamarine",
            "Cornflower Blue",
            "Cadet Blue",
            "Dark Olive Green",
            "Indigo",
            "Medium Turquoise",
            "Dark Slate Blue",
            "Steel Blue",
            "Royal Blue",
            "Turquoise",
            "Medium Sea Green",
            "Lime Green",
            "Dark Slate Gray",
            "Sea Green",
            "Forest Green",
            "Light Sea Green",
            "Dodger Blue",
            "Midnight Blue",
            "Aqua",
            "Cyan",
            "Spring Green",
            "Lime",
            "Medium Spring Green",
            "Dark Turquoise",
            "Deep Sky Blue",
            "Dark Cyan",
            "Teal",
            "Green",
            "Dark Green",
            "Blue",
            "Medium Blue",
            "Dark Blue",
            "Navy",
            "Black"};

    final String[] colorCodeArray = {"#FFFFFF",
            "#FFFFF0",
            "#FFFFE0",
            "#FFFF00",
            "#FFFAFA",
            "#FFFAF0",
            "#FFFACD",
            "#FFF8DC",
            "#FFF5EE",
            "#FFF0F5",
            "#FFEFD5",
            "#FFEBCD",
            "#FFE4E1",
            "#FFE4C4",
            "#FFE4B5",
            "#FFDEAD",
            "#FFDAB9",
            "#FFD700",
            "#FFC0CB",
            "#FFB6C1",
            "#FFA500",
            "#FFA07A",
            "#FF8C00",
            "#FF7F50",
            "#FF69B4",
            "#FF6347",
            "#FF4500",
            "#FF1493",
            "#FF00FF",
            "#FF00FF",
            "#FF0000",
            "#FDF5E6",
            "#FAFAD2",
            "#FAF0E6",
            "#FAEBD7",
            "#FA8072",
            "#F8F8FF",
            "#F5FFFA",
            "#F5F5F5",
            "#F5F5DC",
            "#F5DEB3",
            "#F4A460",
            "#F0FFFF",
            "#F0FFF0",
            "#F0F8FF",
            "#F0E68C",
            "#F08080",
            "#EEE8AA",
            "#EE82EE",
            "#E9967A",
            "#E6E6FA",
            "#E0FFFF",
            "#DEB887",
            "#DDA0DD",
            "#DCDCDC",
            "#DC143C",
            "#DB7093",
            "#DAA520",
            "#DA70D6",
            "#D8BFD8",
            "#D3D3D3",
            "#D2B48C",
            "#D2691E",
            "#CD853F",
            "#CD5C5C",
            "#C71585",
            "#C0C0C0",
            "#BDB76B",
            "#BC8F8F",
            "#BA55D3",
            "#B8860B",
            "#B22222",
            "#B0E0E6",
            "#B0C4DE",
            "#AFEEEE",
            "#ADFF2F",
            "#ADD8E6",
            "#A9A9A9",
            "#A52A2A",
            "#A0522D",
            "#9ACD32",
            "#9932CC",
            "#98FB98",
            "#9400D3",
            "#9370DB",
            "#90EE90",
            "#8FBC8F",
            "#8B4513",
            "#8B008B",
            "#8B0000",
            "#8A2BE2",
            "#87CEFA",
            "#87CEEB",
            "#808080",
            "#808000",
            "#800080",
            "#800000",
            "#7FFFD4",
            "#7FFF00",
            "#7CFC00",
            "#7B68EE",
            "#778899",
            "#708090",
            "#6B8E23",
            "#6A5ACD",
            "#696969",
            "#66CDAA",
            "#6495ED",
            "#5F9EA0",
            "#556B2F",
            "#4B0082",
            "#48D1CC",
            "#483D8B",
            "#4682B4",
            "#4169E1",
            "#40E0D0",
            "#3CB371",
            "#32CD32",
            "#2F4F4F",
            "#2E8B57",
            "#228B22",
            "#20B2AA",
            "#1E90FF",
            "#191970",
            "#00FFFF",
            "#00FFFF",
            "#00FF7F",
            "#00FF00",
            "#00FA9A",
            "#00CED1",
            "#00BFFF",
            "#008B8B",
            "#008080",
            "#008000",
            "#006400",
            "#0000FF",
            "#0000CD",
            "#00008B",
            "#000080",
            "#000000"};
}
